version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: "13.3.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    parameters:
      lane:
        default: "test"
        description: The target Operating System for the heroku binary. Must be one of "linux", "darwin", "win32".
        type: enum
        enum: ["test", "beta", "release"]

    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle update --bundler
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane << parameters.lane >>
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

 

workflows:
  build:
    jobs:
      - build-and-test:
          enum: release
        
          
          
      
