version: 2
jobs:
  build-and-test:
    macos:
      xcode: "13.3.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    parameters:
      fastlane_lane:
        default: "test"
        description: The target Operating System for the heroku binary. Must be one of "linux", "darwin", "win32".
        type: string

    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle update --bundler
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane << parameters.fastlane_lane >>
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

 

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test:
          fastlane_lane: test
          
          
      
